trigger:
- none

pr:
# NOTE: "npm-package" -> "master" after merge
- npm-package

pool:
  vmImage: ubuntu-latest

steps:
# Build the package image.
- script: |
    cd base/package
    export DOCKER_BASE=..
    ./build.sh
  displayName: 'build package image'
