trigger:
- npm-package

pr:
- none

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: 'true'
  clean: 'true'

- script: |
    git config --global user.email 'pipeline@azure.com'
    git config --global user.name 'Azure Pipeline'
  displayName: 'git config'

- script: |
    git checkout -b npm-package
    git push --set-upstream origin npm-package
  displayName: 'git undo detached state'

# Increment version in package.json, git commit, and git tag; see
# https://docs.npmjs.com/cli/v9/commands/npm-version. We don't actually do
# semantic versioning; we just keep incrementing the PATCH version (see
# https://semver.org).
- script: npm version patch
  displayName: 'bump package version'

- script: echo '$(NPM_TOKEN)'
  displayName: 'echo $(NPM_TOKEN)'

# Publish to npm, using the environment variable placeholder in .npmrc; see
# https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow#create-and-check-in-a-project-specific-npmrc-file.
- script: npm publish
  displayName: 'npm publish'
  env:
    NPM_TOKEN: $(NPM_TOKEN)
