jobs:
- job: template_job
  displayName: Provision docker4gis template
  steps:

  # We don't need the code from the repo where this pipeline resides.
  - checkout: none

  - bash: |
        set -x

        # Configure git identity.
        git config --global user.email 'pipeline@azure.com'
        git config --global user.name 'Azure Pipeline'

        # Set Azure CLI defaults for organization and project.
        az devops configure --defaults "organization=$SYSTEM_COLLECTIONURI"
        az devops configure --defaults "project=$SYSTEM_TEAMPROJECT"

        tool() {
            local name=$1
            local file=~/$name
            local code=$2

            echo "#!/bin/bash" > "$file"
            chmod +x "$file"
            echo "$code" >> "$file"
        }

        # Create tool ~/az.
        tool az "
            export AZURE_DEVOPS_EXT_PAT=$PAT
            az \"\$@\"
        "

        # Create tool ~/git_origin (depending on environment variable REPOSITORY).
        tool git_origin "
            # Replace string to insert the \"\$PAT@\" value between the (https):// and
            # the host name in the URI (e.g. https://dev.azure.com/merkatordev/).
            authorised_collection_uri=\${SYSTEM_COLLECTIONURI/'://'/'://'$PAT@}

            echo \"\$authorised_collection_uri\$SYSTEM_TEAMPROJECT/_git/\$REPOSITORY\"
        "

        # Create tool ~/each_repository running a command for each REPOSITORY.
        tool each_repository "
            set -x

            # Loop over a fixed list of REPOSITORY's. 
            for REPOSITORY in ^package cron; do
                # Export the REPOSITORY variable to have it available in tools depending upon it.
                export REPOSITORY

                # Run the given command, with it's optional parameters.
                \"\$@\" || exit
            done
        "
    displayName: 'Configure tools'

  - bash: |
        set -x

        create_repository() {
            # Check if the repo exists, and skip if it does.
            ~/az repos show --repository="$REPOSITORY" 2>&1 &&
                return 0

            # Create the new repo.
            ~/az repos create --name "$REPOSITORY" &&
                # Initialise the new repo.
                (
                    temp=$(mktemp --directory)
                    cd "$temp" || exit
                    git init &&
                        git commit --allow-empty -m "initialise repository" &&
                        git branch -m main &&
                        git remote add origin "$(~/git_origin)" &&
                        git push origin main
                ) &&
                # Set the repo's default branch to "main".
                ~/az repos update --repository="$REPOSITORY" \
                    --default-branch main
        }
        export -f create_repository

        ~/each_repository create_repository
    displayName: 'Create repositories'
